version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.11.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory (and from git)
      - run: npm install
      - run: npm test
#workflows:
#  version: 2
#  build-deploy:
#    jobs:
#      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master

#version: 2
#jobs:
#  build:
#    docker: # use the docker executor type; machine and macos executors are also supported
#      - image: circleci/node:8.11.2 # the primary container, where your job's commands are run
#    steps:
#      - checkout # check out the code in the project directory (and from git)
#      - run: npm install
#      - run: npm test
#      deployment:
#        staging:
#          branch: master
#          heroku:
#            appname: foo-bar-123
#  deploy:
#    steps:
#      - checkout
#      - run:
#          name: Deploy Master to Heroku
#          command: |
#            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
#
#  deployment:
#    staging:
#      branch: master
#      heroku:
#        appname: setupci
